language: python
python:
- "2.7"
- "3.4"
before_install:
- sudo apt-get update -qq
- travis_retry sudo apt-get -y install python-numpy
- travis_retry pip install coveralls
install:
- travis_retry python setup.py develop
script: 
  - coverage run --source=multipletau tests/runtests.py
  - coverage report -m
after_success:
  coveralls --verbose
cache: apt



