language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
notifications:
  email: false
install:
- travis_retry pip install coverage
- travis_retry pip install coveralls
- python setup.py develop
- pip freeze
script:
- coverage run --source=multipletau ./setup.py test
- coverage report -m
after_success:
- coveralls --verbose

